# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/JW/Desktop/MKEL1183 Advanced Computer Architecture/Assignment1/Basic_CPU/Basic_CPU.cache/wt} [current_project]
set_property parent.project_path {C:/Users/JW/Desktop/MKEL1183 Advanced Computer Architecture/Assignment1/Basic_CPU/Basic_CPU.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.3 [current_project]
set_property ip_output_repo {c:/Users/JW/Desktop/MKEL1183 Advanced Computer Architecture/Assignment1/Basic_CPU/Basic_CPU.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/JW/Desktop/MKEL1183 Advanced Computer Architecture/Assignment1/Basic_CPU/Basic_CPU.srcs/sources_1/new/ALU.sv}
  {C:/Users/JW/Desktop/MKEL1183 Advanced Computer Architecture/Assignment1/Basic_CPU/Basic_CPU.srcs/sources_1/new/DataMemory.sv}
  {C:/Users/JW/Desktop/MKEL1183 Advanced Computer Architecture/Assignment1/Basic_CPU/Basic_CPU.srcs/sources_1/new/InstructionMemory.sv}
  {C:/Users/JW/Desktop/MKEL1183 Advanced Computer Architecture/Assignment1/Basic_CPU/Basic_CPU.srcs/sources_1/new/Registers.sv}
  {C:/Users/JW/Desktop/MKEL1183 Advanced Computer Architecture/Assignment1/Basic_CPU/Basic_CPU.srcs/sources_1/new/Top.sv}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top Top -part xc7z020clg484-1


write_checkpoint -force -noxdef Top.dcp

catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
